name: Format Filenames

on:
  push:
    paths:
      - 'java/**/*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Rename files in java folder using Bash
        run: |
          # Get a list of files changed in the last commit
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          
          # Debug: Print changed files
          echo "Changed files:"
          echo "$changed_files"
          echo "------"
          IFS=$'\n'
          for file in $changed_files; do
            echo "Processing: $file" # Debug output
            
            # Check if file exists
            if [[ ! -f $file ]]; then
              echo "Skipping $file as it does not exist." # Debug output
              continue
            fi
            
            # Extract just the filename from the path
            filename=$(basename "$file")
            
            # Skip files ending with .java
            if [[ $filename == *.java || $filename == *.md ]]; then
              continue
            fi
            
            # Check if the file matches the desired pattern
            if [[ $filename =~ ^([0-9]+)\.\ (.*)$ ]]; then
              number=$(printf "%04d" ${BASH_REMATCH[1]})
              name=${BASH_REMATCH[2]}
              newFilename="${number}. ${name}.java"
          
              # Construct the new path
              newPath="java/$newFilename"
          
              if [[ "$file" != "$newPath" ]]; then
                echo "Renaming $file to $newPath" # Debug output
                mv "$file" "$newPath"
              fi
            fi
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Format filenames in java folder" || echo "No changes to commit"
          git push
