name: Rename Java Files

on:
  push:
    paths:
      - 'java/**' # This will run the action only for Java file pushes
      - '!*.md'

jobs:
  format-filenames:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Format filenames of changed files in 'java' folder
      run: |
        changed_files=$(git diff HEAD^ --name-only -- 'java/**')
        for file in $changed_files; do
          # Check if the file starts with up to 3 digits and doesn't end with .java
          if [[ $file =~ java/[0-9]{1,3}\.\ .*$ ]]; then
            
            echo "Processing file: $file"
            
            # Extract the numeric part and the rest of the filename
            number_part="${file%%.*}"
            number_part="${number_part#java/}"  # Remove the leading "java/"
            rest_part="${file#*. }"
            rest_part="${rest_part%.java}"  # Remove the ".java" if it exists

            # Format with padding zeros, prepend with 'java/' and append ".java"
            newname=$(printf "java/%04d. %s.java" "$number_part" "$rest_part")
            
            echo "Renaming $file to $newname"
            git mv "$file" "$newname"
          fi
        done

    - name: Commit and push if changes were made
      run: |
        git diff --exit-code || git commit -am "Formatted filenames in 'java' folder"
        git push origin

