name: Rename Java Files

on:
  push:
    paths:
      - 'java/*.java' # This will run the action only for Java file pushes

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rename files
      run: |
        for file in $(git diff --name-only HEAD^ HEAD); do
          # Check if the file starts with up to 3 digits followed by a non-digit character
          if [[ $file =~ ^[0-9]{1,3}[^0-9].java$ ]]; then
            newname=$(printf "%04d%s" "${file%%[^0-9]*}" "${file#*[0-9]}")
            echo "Renaming $file to $newname"
            git mv "$file" "$newname"
          fi
        done

    - name: Commit and push if changes were made
      run: |
        git diff --exit-code || git commit -am "Renamed files"
        git push origin
