name: Format Java File Names

on:
  push:
    paths:
      - 'java/**'
      - '!*.md'

jobs:
  format-filenames:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get list of changed files
      id: getfile
      uses: trilom/file-changes-action@v1.2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: 'json'
        
    - name: Format filenames of changed files in 'java' folder and its subfolders
      run: |
        changed_files=$(echo '${{ steps.getfile.outputs.files }}' | jq -r '.[] | select(startswith("java/"))')
        for file in $changed_files; do
          # Check if the file starts with up to 3 digits and doesn't end with .java
          if [[ $file =~ java/[0-9]{1,3}\.\ .*$ ]]; then
            # Extract the numeric part and the rest of the filename
            number_part="${file%%.*}"
            number_part="${number_part#java/}"  # Remove the leading "java/"
            rest_part="${file#*. }"
            rest_part="${rest_part%.java}"  # Remove the ".java" if it exists

            # Format with padding zeros, prepend with 'java/' and append ".java"
            newname=$(printf "java/%04d. %s.java" "$number_part" "$rest_part")
            
            echo "Renaming $file to $newname"
            git mv "$file" "$newname"
          fi
        done

    - name: Commit and push if changes were made
      run: |
        git diff --exit-code || git commit -am "Formatted filenames in 'java' folder"
        git push origin
